-- ╔══════════════════════════════════════════════════════════════════╗
-- ║  Porres F1 — Supabase Schema                                   ║
-- ║  Run this in Supabase SQL Editor to create all tables           ║
-- ╚══════════════════════════════════════════════════════════════════╝

-- 1. Predictions: each user's picks per session per GP
CREATE TABLE IF NOT EXISTS predictions (
  id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year      INT     NOT NULL,
  gp_number INT     NOT NULL,
  "user"    TEXT    NOT NULL,
  session   TEXT    NOT NULL,   -- Race, Qualifying, Sprint, SS
  picks     JSONB   NOT NULL,   -- ["VER","NOR","LEC", ...]
  extra     JSONB,              -- {"type":"dnf","driver":"PER"}
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(year, gp_number, "user", session)
);

-- 2. Season Scores: calculated points per user per GP
CREATE TABLE IF NOT EXISTS season_scores (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year             INT   NOT NULL,
  gp_number        INT   NOT NULL,
  "user"           TEXT  NOT NULL,
  points_breakdown JSONB NOT NULL,
  total_points     FLOAT NOT NULL,
  calculated_at    TIMESTAMPTZ DEFAULT now(),
  UNIQUE(year, gp_number, "user")
);

-- ── Row Level Security ──────────────────────────────────────────
ALTER TABLE predictions   ENABLE ROW LEVEL SECURITY;
ALTER TABLE season_scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all on predictions"   ON predictions   FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on season_scores" ON season_scores  FOR ALL USING (true) WITH CHECK (true);

-- ── Helper: auto-update updated_at ─────────────────────────────
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER predictions_updated_at
  BEFORE UPDATE ON predictions
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();
